### ISSUE TITLE
403 on S3 URLs

### ISSUE THREAD

**Issue by CyBeRoni** [ForbesLindesay/thread-sleep#14] opened 2017-12-13 15:29 UTC
Attempting to install thread-sleep currently tries to download this file:

```
node-pre-gyp info check checked for "/app/node_modules/thread-sleep/lib/binding/Release/node-v59-linux-x64/thread_sleep.node" (not found)
node-pre-gyp http GET https://node-pre-gyp-forbeslindesay.s3.amazonaws.com/thread_sleep/v1.0.4/Release/thread_sleep-v1.0.4-node-v59-linux-x64.tar.gz
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
```

Which results in an Amazon S3 error:

```
$ curl -v https://node-pre-gyp-forbeslindesay.s3.amazonaws.com/thread_sleep/v1.0.4/Release/thread_sleep-v1.0.4-node-v59-linux-x64.tar.gz

HTTP/1.1 403 Forbidden
```

**Comment by umrysh** [comment] 2018-04-22 14:30
I thought I would mention I was running into the exact same issue and it turned out it was actually being caused by the [try-thread-sleep](https://github.com/ForbesLindesay/try-thread-sleep) package. One of the packages I was installing had try-thread-sleep as a dependency which (as far as I can tell) has a sole purpose to load the thread-sleep package. However try-thread-sleep tries to load the old 1.0.4 version and not version 2.0.0 of thread-sleep.

I [forked](https://github.com/umrysh/try-thread-sleep) try-thread-sleep and updated it to use version 2. I installed my fork using `npm install git+https://github.com/umrysh/try-thread-sleep.git` and then retried installing my original package and everything worked :)

Hopefully this helps someone else

**Comment by ForbesLindesay** [comment] 2018-05-13 14:20
try-thread-sleep has been updated now, and the latest version of thread-sleep no longer hits any S3 URLs, so I'm going to close this.

**Closed as completed by ForbesLindesay** 2018-05-13 14:20 UTC
